x-ollama-base: &ollama-base
  image: "alpine/ollama:${OLLAMA_VERSION:-latest}"
  container_name: "${NAMESPACE}_ollama"
  ports:
    - "11434:11434"
  env_file: .env
  tty: true
  init: true
  pull_policy: always
  entrypoint: [ "/bin/sh", "-c" ]
  command: >
    "ollama serve & sleep 5 && ollama pull mistral:instruct && wait"
  volumes:
    - ~/.ollama:/root/.ollama
  healthcheck:
    test: ["CMD-SHELL", "nc -w 2 -z localhost 11434"]
    start_period: 1m
    interval: 30s
    timeout: 5s
    retries: 3

x-ollama-gpu-deploy: &ollama-gpu-deploy
  deploy:
    resources:
      reservations:
        devices:
          - count: 1
            capabilities:
              - gpu

services:
  
  ollama:
    <<: *ollama-base
    profiles:
      - cpu

  ollama-nvidia:
    <<: [*ollama-base, *ollama-gpu-deploy]
    profiles:
      - nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER:-nvidia}
              count: 1
              capabilities:
                - gpu

  n8n:
    container_name: ${NAMESPACE}_n8n
    image: n8nio/n8n:${N8N_VERSION}
    hostname: n8n
    pull_policy: always
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n_shared:/home/node/.n8n/workflows
    depends_on:
      webserver:
        condition: service_healthy
    ports:
      - 5678:5678
    entrypoint: ["/bin/sh", "-c"]
    command: ["n8n import:workflow --input=/home/node/.n8n/workflows/papeercuts-no-more.json && n8n"]

  broker:
    container_name: ${NAMESPACE}_broker
    image: docker.io/library/redis:${REDIS_VERSION}
    pull_policy: always
    env_file: .env
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    container_name: ${NAMESPACE}_db
    image: docker.io/library/postgres:${POSTGRES_VERSION}
    pull_policy: always
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres/pgdata/_data:/var/lib/postgresql/data
      - ./.docker/postgres/pg-init.sql:/docker-entrypoint-initdb.d/99-clear-collations.sql
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -p 5432 -U ${POSTGRES_USER:-paperless}"]
      interval: 10s
      timeout: 5s
      retries: 5

  webserver:
    container_name: ${NAMESPACE}_webserver
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    pull_policy: always
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy
    ports:
      - 8010:8000
    volumes:
      - ./.docker/webserver/volumes/consume:/usr/src/paperless/consume
      - ./.docker/webserver/volumes/data/_data:/usr/src/paperless/data
      - ./.docker/webserver/volumes/export:/usr/src/paperless/export
      - ./.docker/webserver/volumes/media:/usr/src/paperless/media
      - ./.docker/webserver/custom-auth:/custom-cont-init.d:ro
    healthcheck:
      test: ["CMD", "python", "-c", "import socket,sys; s=socket.socket(); s.settimeout(2); rc=s.connect_ex(('127.0.0.1',8000)); s.close(); sys.exit(0 if rc==0 else 1)"]
      interval: 10s
      timeout: 5s
      retries: 5

  scanner:
    container_name: ${NAMESPACE}_scanner
    image: sbs20/scanservjs:${SCANNER_VERSION}
    pull_policy: always
    env_file: .env
    privileged: true
    network_mode: "host"
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    ports:
      - 8080:8080

volumes:
  redisdata:
  n8n_data:
