x-ollama-base: &ollama-base
  image: "alpine/ollama:${OLLAMA_VERSION:-latest}"
  container_name: "${NAMESPACE}_ollama"
  ports:
    - "11434:11434"
  env_file: .env
  tty: true
  init: true
  restart: unless-stopped
  pull_policy: always
  entrypoint: [ "/bin/sh", "-c" ]
  command: >
    "ollama serve & sleep 5 && ollama pull mistral:instruct && wait"
  volumes:
    - ~/.ollama:/root/.ollama

x-ollama-gpu-deploy: &ollama-gpu-deploy
  deploy:
    resources:
      reservations:
        devices:
          - count: 1
            capabilities:
              - gpu

services:
  
  ollama:
    <<: *ollama-base
    profiles:
      - cpu

  ollama-nvidia:
    <<: [*ollama-base, *ollama-gpu-deploy]
    profiles:
      - nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER:-nvidia}
              count: 1
              capabilities:
                - gpu

  ollama-amd:
    <<: [*ollama-base, *ollama-gpu-deploy]
    profiles:
      - amd
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_AMD_DRIVER:-k8s.io/rocm}
              count: 1
              capabilities:
                - gpu
  n8n:
    container_name: ${NAMESPACE}_n8n
    image: n8nio/n8n:${N8N_VERSION}
    hostname: n8n
    pull_policy: always
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n_shared:/home/node/.n8n/workflows
    depends_on:
      webserver:
        condition: service_healthy
    ports:
      - 5678:5678

  broker:
    container_name: ${NAMESPACE}_broker
    image: docker.io/library/redis:${REDIS_VERSION}
    pull_policy: always
    env_file: .env
    volumes:
      - redisdata:/data

  db:
    container_name: ${NAMESPACE}_db
    image: docker.io/library/postgres:${POSTGRES_VERSION}
    pull_policy: always
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata/_data:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -p 5432 -U ${POSTGRES_USER:-paperless}"]
      interval: 10s
      timeout: 5s
      retries: 5

  webserver:
    container_name: ${NAMESPACE}_webserver
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    pull_policy: always
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy
    ports:
      - 8010:8000
    volumes:
      - ./data/_data:/usr/src/paperless/data
      - ./scans:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ~/Dokumente/Scans:/usr/src/paperless/consume
      - ./.docker/custom-auth:/custom-cont-init.d:ro
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8000"]
      interval: 10s
      timeout: 5s
      retries: 5

  scanner:
    container_name: ${NAMESPACE}_scanner
    image: sbs20/scanservjs:${SCANNER_VERSION}
    pull_policy: always
    env_file: .env
    privileged: true
    network_mode: "host"
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    ports:
      - 8080:8080

volumes:
  redisdata:
  n8n_data:
